# Generated by Django 2.2.6 on 2019-10-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='freeuse',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='img',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
