# Generated by Django 2.2.6 on 2019-10-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageposts', '0002_auto_20191021_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='long_description',
            field=models.TextField(default=models.TextField(max_length=100), max_length=1000),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
