# Generated by Django 2.2.6 on 2019-11-03 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageposts", "0009_imagepost_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagepost",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
