# Generated by Django 2.2 on 2019-12-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageposts', '0010_auto_20191103_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='favs',
            field=models.IntegerField(default=0),
        ),
    ]
