# Generated by Django 2.2.6 on 2020-01-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageposts', '0013_auto_20191220_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='license_text',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='title',
            field=models.TextField(max_length=30),
        ),
    ]
