# Generated by Django 2.2.6 on 2020-01-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageposts", "0014_auto_20200117_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagepost",
            name="tags",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
