# Generated by Django 2.2.6 on 2019-10-31 12:47

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191031_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=django_fields.fields.DefaultStaticImageField(upload_to='profile_imgs'),
        ),
    ]
