# Generated by Django 2.2.6 on 2019-11-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_auto_20191101_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="follow",
            field=models.ManyToManyField(related_name="follows", to="user.Profile"),
        ),
    ]
