# Generated by Django 2.2.6 on 2019-12-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_follower"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
