# Generated by Django 2.2.6 on 2019-12-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_profile_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_pro",
            field=models.BooleanField(default=False),
        ),
    ]
