# Generated by Django 2.2.6 on 2019-12-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20191205_0213'),
        ('user', '0011_profile_is_pro'),
    ]

    operations = [
    ]
