# Generated by Django 2.2.6 on 2019-12-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_auto_20191206_1411"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="follow",
        ),
    ]
